#
# Prepares a Python development environment
#
# (libyaml-dev is a depedency for PyYAML)
#

- name: install python packages
  apt: 'pkg={{ item }} state=latest'
  become: yes
  with_items:
    - libyaml-dev
    - pypy
    - pypy-dev
    - python
    - python-dev
    - python-pip
    - python-pip-whl
    - python3.4
    - python3.4-dev
    - python3.5
    - python3.5-dev

#
# Install virtualenv and virtualenvwrapper
#

- name: virtualenv | install packages
  apt: 'pkg={{ item }} state=latest'
  become: yes
  with_items:
    - python-virtualenv
    - virtualenvwrapper
